version: '2.1'
services:
  customerquery:
    build: customers/
    depends_on:
      - mongo
      - rabbitmq
    mem_limit: 700m
    ports:
      - "8081:8080"
    environment:
      - MONGO_HOST=mongo
      - ES_JAVA_OPTS= "-Xms150mb -Xmx150mb"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://:5000"
        tag: "customer-query-server"

  customercmd:
    build: customer.cmd/
    depends_on:
      - mongo
      - rabbitmq
    mem_limit: 700m
    ports:
      - "8079:8080"
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
      - ES_JAVA_OPTS= "-Xms150mb -Xmx150mb"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://:5000"
        tag: "customer-cmd-server"

  accountcmd:
    build: account.cmd/
    depends_on:
      - mongo
      - rabbitmq
    mem_limit: 700m
    ports:
      - "8083:8080"
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://:5000"
        tag: "account-cmd-server"

  accountquery:
    build: account.query/
    depends_on:
      - mongo
      - rabbitmq
    mem_limit: 700m
    ports:
      - "8084:8080"
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
      - ES_JAVA_OPTS= "-Xms150mb -Xmx150mb"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://:5000"
        tag: "acount-query-server"

  transactionserver:
    build: transactions/
    depends_on:
      - mongo
    mem_limit: 700m
    ports:
      - "8085:8080"
    environment:
      - MONGO_HOST=mongo
      - ES_JAVA_OPTS= "-Xms150mb -Xmx150mb"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://:5000"
        tag: "transaction-server"

  mongo:
    image: 'mongo:3.4.1'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo:
