spring:
  application:
    name: accountcmd
  data:
    mongodb:
      database: ${spring.application.name}
      host: localhost
      port: 27017
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    auto-config:
      default-exchange:
        type: fanout
        dead-letter-enabled: true
      dead-letter-config:
        dead-letter-exchange:
          name: dead-letter-${spring.application.name}
          auto-delete: true
          durable: false
        queue-postfix: .dlq

axon:
  cluster-name: ${spring.application.name}
  eventstore:
    mongo:
      connections:
        default:
          uri: mongodb://localhost:27017/${spring.application.name}
          aggregates:
            - Account
amqp:
  events:
    host: localhost
    exchange-name: eventBus-account
    queue-name: eventQueue-account
    handlers:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: false
  instance:
    preferIpAddress: true

endpoints:
  health:
    sensitive:  false

management:
  security:
    enabled: false
