spring:
  profiles:
    include: default
  data:
    mongodb:
      host: mongo
  rabbitmq:
    host: rabbitmq

axon:
  eventstore:
    mongo:
      connections:
        default:
          uri: mongodb://mongo:27017/${spring.application.name}
amqp:
  events:
    host: rabbitmq

eureka:
  client:
    serviceUrl:
      defaultZone: http://discoveryservice:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true

endpoints:
  health:
    sensitive:  false

server:
  port: 8080

management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include: health,info,metrics
    shutdown:
      enabled: true

hosts:
  account-cmd: accountcmd:8089
  account-query: accountquery:8084
  customers: customers:8082