spring:
  application:
    name: customercmd
  data:
    mongodb:
      database: ${spring.application.name}
      host: localhost
      port: 27017
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

axon:
  cluster-name: ${spring.application.name}
  eventstore:
    mongo:
      connections:
        default:
          uri: mongodb://localhost:27017/${spring.application.name}
          aggregates:
            - Customer
amqp:
  events:
    host: localhost
    exchange-name: eventBus-customer
    queue-name: eventQueue-customer
    handlers:

endpoints:
  health:
    sensitive:  false

management:
  security:
    enabled: false
