spring:
  profiles:
    include: default
  data:
    mongodb:
      host: mongo
  rabbitmq:
    host: rabbitmq

axon:
  eventstore:
    mongo:
      connections:
        default:
          uri: mongodb://mongo:27017/${spring.application.name}
amqp:
  events:
    host: rabbitmq

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true